AWSTemplateFormatVersion: 2010-09-09
Description: This is a S3 bucket where we are going to deploy the files of our application
Parameters:
  BucketName:
    Type: String
    Default: andresbarreto
    AllowedPattern: ^[A-Za-z0-9]*$
    MinLength: 1
    MaxLength: 15
    Description: This the name of the bucket
Resources:
  BucketS3New:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref BucketName
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - POST
              - PUT
              - HEAD 
              - DELETE
            AllowedOrigins: 
              - '*'
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
Outputs:
  BucketName:
    Value: !Ref BucketS3New
    Export:
      Name: BucketName
