AWSTemplateFormatVersion: 2010-09-09
Description: This is a S3 bucket where we are going to deploy the files of our application
Metadata: 
Parameters:
  BucketName:
    Type: String
    Default: andresbarreto
    AllowedPattern: ^[A-Za-z0-9]*$
    MinLength: 1
    MaxLength: 15
    Description: This the name of the bucket
  AllowedOriginsWebsite:
    Type: List<String>
    Default: 
      - andresbarreto
      - cloudfront
    AllowedPattern: ^[A-Za-z0-9]*$
    MinLength: 1
    MaxLength: 15
    Description: List of origins the bucket can be connected to.
Resources:
  BucketS3:
    Type: 'AWS::S3::Bucket'
    Properties: 
      AccessControl: PublicRead
      BucketName: !Ref BucketName
      CorsConfiguration: 
        CorsRules: 
          - AllowedMethods: 
            - GET
            - POST
            - PUT
            - HEAD 
            - DELETE
          - AllowedOrigins: !Ref AllowedOriginsWebsite
      WebsiteConfiguration: 
        ErrorDocument: index.html
        IndexDocument: index.html