AWSTemplateFormatVersion: 2010-09-09
Description: This is a S3 bucket where we are going to deploy the files of our application
Parameters:
  BucketName:
    Type: String
    Default: andresbarreto
    AllowedPattern: ^[A-Za-z0-9]*$
    MinLength: 1
    MaxLength: 15
    Description: This the name of the bucket
  AllowedOrigins:
    Type: List<String>
    Default: '*'
    Description: Origins allowed to request
Resources:
  BucketS3New:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref BucketName
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - POST
              - PUT
              - HEAD 
              - DELETE
            AllowedOrigins: !Ref AllowedOrigins
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
  CloudFrontNew:
    Type: AWS::CloudFront::Distribution
    Properties: 
      DistributionConfig: 
        CacheBehaviors: 
          - AllowedMethods: '*'
          - PathPattern: '*'
        CustomErrorResponses: 
          - ErrorCode: 400
            ResponseCode: 200
            ResponsePagePath: index.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: index.html
          - ErrorCode: 405
            ResponseCode: 200
            ResponsePagePath: index.html
        DefaultRootObject: index.html
        Enabled: yes
        Origins: 
          - DomainName: !Ref BucketName
            Id: !Ref BucketName
            PriceClass: PriceClass_All
Outputs:
  BucketName:
    Value: !Ref BucketS3New
    Export:
      Name: BucketName
